version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    ports:
      - 8080:80