version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  php-fpm:
    image: php:8.2-fpm
    environment:
      - PORT=9000  # ou a porta que você deseja, ajuste conforme necessário
    expose:
      - "9000"  # A porta que o PHP-FPM estará escutando internamente

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
