<<<<<<< HEAD


=======
>>>>>>> d1d48a76316fabed94a0632a26bf01d02dff9494
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
<<<<<<< HEAD
      - .:/var/www/html  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    ports:
      - 8080:80
=======
      - .:/var/www/html

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - 8080:80

>>>>>>> d1d48a76316fabed94a0632a26bf01d02dff9494
